### PR TITLE
refactoring to TemporalType enum

### PR DESCRIPTION
**Pull request by daviddbal**
needed to build jfxtras-labs

### CODE REVIEW

**Comment by tbee** [comment]
Yeah. The code no longer compiles after merging. The combine method is not found.

**Comment by tbee** [comment]
The AgendaTemporalConversionTest did not longer compile. This exactly is the reason why I'm hesitant which merging the PR's.

**Comment by daviddbal** [comment]
That is probably due to the method name change.  I'll fix it.  That is happening because I can't run the tests in jfxtras on my end.  I literally move the tests from jfxtras into jfxtras-labs, fix them, and then move them back.  I need to get the jfxtras tests running.
-David 

```
On Thursday, March 10, 2016 12:04 PM, Tom Eugelink <notifications@github.com> wrote:
```

 The AgendaTemporalConversionTest did not longer compile. This exactly is the reason why I'm hesitant which merging the PR's.—

**Comment by daviddbal** [comment]
I fixed the broken tests.  I'll try to make sure I have a proper build of jfxtras and have run the tests before I do any more PRs.
-David 

```
On Thursday, March 10, 2016 12:04 PM, Tom Eugelink <notifications@github.com> wrote:
```

 The AgendaTemporalConversionTest did not longer compile. This exactly is the reason why I'm hesitant which merging the PR's.—

**Comment by tbee** [comment]
You need to create a single or two separate new PRs. I've reverted the original one, so the new one only modifies the test and then breaks the code.

**Pull request merged**
